# Generated by Django 5.2.3 on 2025-06-20 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
