# Generated by Django 5.2.3 on 2025-06-23 17:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0002_alter_foodlog_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=100)),
                ('severity', models.IntegerField(help_text='Rate severity from 1 (mild) to 10 (severe)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('food_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='healthapp.foodlog')),
            ],
        ),
    ]
